import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  mapWrapper: {
    height: 150,
    width: "100%",
    borderRadius: 12,
    overflow: "hidden",
    marginTop: 5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#EEE",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  navOverlayButton: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "#0E011A", // Couleur de ton thème
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  navOverlayText: {
    color: "white",
    fontWeight: "bold",
    marginLeft: 6,
    fontSize: 12,
  },
  container: { flex: 1, backgroundColor: "#fff" },
  imageContainer: {
    width: "100%",
    height: 220,
    overflow: "hidden",
  },
  image: { width: "100%", height: "100%" },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 16,
    marginHorizontal: 16,
    color: "#0E011A",
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 16,
    marginTop: 8,
  },
  tag: {
    backgroundColor: "#1C52D2",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    marginRight: 6,
    marginBottom: 6,
  },
  tagText: {
    color: "white",
    fontSize: 12,
    fontWeight: "600",
  },
  description: {
    fontSize: 16,
    marginHorizontal: 16,
    marginTop: 8,
    color: "#555",
    lineHeight: 22,
  },
  infoBlock: {
    marginHorizontal: 16,
    marginTop: 20,
    paddingVertical: 16,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#F7F7F7",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    flexWrap: "wrap",
  },
  infoText: {
    marginLeft: 10,
    fontSize: 15,
    color: "#0E011A",
    flex: 1,
    flexWrap: "wrap",
  },
  calendarButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1C52D2",
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    marginLeft: 8,
  },
  calendarButtonText: {
    color: "white",
    fontSize: 14,
    marginLeft: 4,
    fontWeight: "600",
  },
  clubContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 16,
    marginTop: 8,
    paddingVertical: 6,
  },
  clubImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 8,
  },
  clubName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0E011A",
  },
});