export const USER_LOCATION = {
  latitude: 48.8566,
  longitude: 2.3522,
};

export const clubs = [
  {
    id: "1",
    name: "Paris Football Club",
    bannerImageUrl: "https://picsum.photos/seed/club1/400/200",
    imageUrl: "https://picsum.photos/seed/avatar1/100",
    addressLine1: "17 Rue de la Porte de Montreuil",
    city: "Paris",
    latitude: 48.857,
    longitude: 2.410,
    type: "Football",
  },
  {
    id: "2",
    name: "Montmartre Yoga Studio",
    bannerImageUrl: "https://picsum.photos/seed/club2/400/200",
    imageUrl: "https://picsum.photos/seed/avatar2/100",
    addressLine1: "22 Rue des Abbesses",
    city: "Paris",
    latitude: 48.886,
    longitude: 2.343,
    type: "Yoga",
  },
  {
    id: "3",
    name: "Paris Tennis Academy",
    bannerImageUrl: "https://picsum.photos/seed/club3/400/200",
    imageUrl: "https://picsum.photos/seed/avatar3/100",
    addressLine1: "15 Avenue de Suffren",
    city: "Paris",
    latitude: 48.851,
    longitude: 2.298,
    type: "Tennis",
  },
  {
    id: "4",
    name: "Bastille CrossFit",
    bannerImageUrl: "https://picsum.photos/seed/club4/400/200",
    imageUrl: "https://picsum.photos/seed/avatar4/100",
    addressLine1: "8 Rue de la Roquette",
    city: "Paris",
    latitude: 48.853,
    longitude: 2.372,
    type: "Crossfit",
  },
  {
    id: "5",
    name: "Seine Running Club",
    bannerImageUrl: "https://picsum.photos/seed/club5/400/200",
    imageUrl: "https://picsum.photos/seed/avatar5/100",
    addressLine1: "10 Quai de la Tournelle",
    city: "Paris",
    latitude: 48.851,
    longitude: 2.352,
    type: "Running",
  },
  {
    id: "6",
    name: "Lyon Basketball Academy",
    bannerImageUrl: "https://picsum.photos/seed/club6/400/200",
    imageUrl: "https://picsum.photos/seed/avatar6/100",
    addressLine1: "32 Rue Garibaldi",
    city: "Lyon",
    latitude: 45.764,
    longitude: 4.835,
    type: "Basketball",
  },
  {
    id: "7",
    name: "Marseille Swimming Club",
    bannerImageUrl: "https://picsum.photos/seed/club7/400/200",
    imageUrl: "https://picsum.photos/seed/avatar7/100",
    addressLine1: "5 Boulevard Michelet",
    city: "Marseille",
    latitude: 43.270,
    longitude: 5.395,
    type: "Natation",
  },
  {
    id: "8",
    name: "Bordeaux Cycling Team",
    bannerImageUrl: "https://picsum.photos/seed/club8/400/200",
    imageUrl: "https://picsum.photos/seed/avatar8/100",
    addressLine1: "18 Rue Sainte-Catherine",
    city: "Bordeaux",
    latitude: 44.838,
    longitude: -0.579,
    type: "Cyclisme",
  },
  {
    id: "9",
    name: "Lille Volleyball Club",
    bannerImageUrl: "https://picsum.photos/seed/club9/400/200",
    imageUrl: "https://picsum.photos/seed/avatar9/100",
    addressLine1: "12 Rue Nationale",
    city: "Lille",
    latitude: 50.629,
    longitude: 3.057,
    type: "Volley",
  },
  {
    id: "10",
    name: "Nice Beach Fitness",
    bannerImageUrl: "https://picsum.photos/seed/club10/400/200",
    imageUrl: "https://picsum.photos/seed/avatar10/100",
    addressLine1: "Promenade des Anglais",
    city: "Nice",
    latitude: 43.695,
    longitude: 7.265,
    type: "Fitness",
  }
];

export const events = [
  {
    id: "101",
    name: "Tournoi de Football Paris",
    bannerImageUrl: "https://picsum.photos/seed/event1/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar1/100",
    addressLine1: "Stade Charlety",
    city: "Paris",
    latitude: 48.819,
    longitude: 2.343,
    type: "Football",
  },
  {
    id: "102",
    name: "Marathon de Paris",
    bannerImageUrl: "https://picsum.photos/seed/event2/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar2/100",
    addressLine1: "Champs-Élysées",
    city: "Paris",
    latitude: 48.869,
    longitude: 2.307,
    type: "Running",
  },
  {
    id: "103",
    name: "Compétition de Crossfit Bastille",
    bannerImageUrl: "https://picsum.photos/seed/event3/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar3/100",
    addressLine1: "Crossfit Bastille",
    city: "Paris",
    latitude: 48.853,
    longitude: 2.372,
    type: "Crossfit",
  },
  {
    id: "104",
    name: "Open Tennis Lyon",
    bannerImageUrl: "https://picsum.photos/seed/event4/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar4/100",
    addressLine1: "Tennis Club Lyon",
    city: "Lyon",
    latitude: 45.764,
    longitude: 4.835,
    type: "Tennis",
  },
  {
    id: "105",
    name: "Tournoi Basket Street Lille",
    bannerImageUrl: "https://picsum.photos/seed/event5/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar5/100",
    addressLine1: "Place de la République",
    city: "Lille",
    latitude: 50.629,
    longitude: 3.057,
    type: "Basketball",
  },
  {
    id: "106",
    name: "Course Cycliste Bordeaux",
    bannerImageUrl: "https://picsum.photos/seed/event6/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar6/100",
    addressLine1: "Quais de Bordeaux",
    city: "Bordeaux",
    latitude: 44.838,
    longitude: -0.579,
    type: "Cyclisme",
  },
  {
    id: "107",
    name: "Tournoi Volley Plage Nice",
    bannerImageUrl: "https://picsum.photos/seed/event7/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar7/100",
    addressLine1: "Plage de Nice",
    city: "Nice",
    latitude: 43.695,
    longitude: 7.265,
    type: "Volley",
  },
  {
    id: "108",
    name: "Festival Yoga Paris",
    bannerImageUrl: "https://picsum.photos/seed/event8/400/200",
    imageUrl: "https://picsum.photos/seed/eventavatar8/100",
    addressLine1: "Parc des Buttes Chaumont",
    city: "Paris",
    latitude: 48.879,
    longitude: 2.381,
    type: "Yoga",
  }
];